# Generated by Django 6.0.5 on 2026-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='Upcoming', max_length=20),
        ),
    ]
