# Generated by Django 6.0.5 on 2026-05-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
