# Generated by Django 6.0.5 on 2026-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_feedback_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='student_email',
            field=models.EmailField(default='temp@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
